language: python

python:
  - "2.7"
  - "3.5"

os:
  - linux

sudo: false

addons:
  apt:
    packages:
      - libboost-all-dev
      - nvidia-common
      - nvidia-current
      - nvidia-cuda-toolkit
      - nvidia-cuda-dev
env:
    - CUDA=yes
    - CUDA=no

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

install:
  - conda install python=$TRAVIS_PYTHON_VERSION six numpy scipy cython
  - conda info -a
  - cd build/linux
  - ./autogen.sh
  - if [ $CUDA == yes ]; then ./configure --prefix=$HOME/astra --with-python --with-cuda; else ./configure --prefix=$HOME/astra --with-python --without-cuda; fi
  - make -j 4
  - make install

script:
  - LD_LIBRARY_PATH=$HOME/astra/lib/:$LD_LIBRARY_PATH PYTHONPATH=$HOME/astra/python/:$PYTHONPATH python -c "import astra"
